<a href="https://colab.research.google.com/github/Ragul-S-2025/ML/blob/main/Feautre_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import Libraries and Load datasets

import pandas as pd

df = pd.read_excel('/content/Data_Train.xlsx')

In [3]:
df.shape

(10683, 11)

In [7]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Price
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,3897
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,7662
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,13882
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,6218
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,13302

In [ ]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [9]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Price
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,3897
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,7662
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,13882
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,6218
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,13302

In [10]:
# Fill missing values in 'Total_Stops' with the mode and 'Route' with 'Unknown'
df['Total_Stops'] =df['Total_Stops'].fillna(df['Total_Stops'].mode()[0])
df['Route'] = df['Route'].fillna('Unknown')

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Airline']=le.fit_transform(df['Airline'])
df['Source']=le.fit_transform(df['Source'])
df['Destination']=le.fit_transform(df['Destination'])
df["Route"]=le.fit_transform(df["Route"])
df["Total_Stops"]=le.fit_transform(df["Total_Stops"])

In [15]:
df.isnull().sum()

Airline        0
Source         0
Destination    0
Route          0
Duration       0
Total_Stops    0
Price          0
dtype: int64

In [16]:
df.head()

   Airline  Source  Destination  Route Duration  Total_Stops  Price
0        3       0            5     18   2h 50m            4   3897
1        1       3            0     84   7h 25m            1   7662
2        4       2            1    118      19h            1  13882
3        3       3            0     91   5h 25m            0   6218
4        3       0            5     29   4h 45m            0  13302

In [17]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Duration', 'Total_Stops',
       'Price'],
      dtype='object')

In [18]:

X=df[['Airline','Duration','Source', 'Destination','Route','Total_Stops']]

In [19]:
y=df[['Price']]

**Feature** Selection

 Recursive Feature Elimination

In [20]:
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)


        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)
        return X_train, X_test, y_train, y_test

In [21]:
def classification_f1(classifier, X_test, y_test):
    y_pred = classifier.predict(X_test)
    from sklearn.metrics import f1_score
    f1 = f1_score(y_test, y_pred, average='weighted')
    return f1

In [22]:
def Linear(X_train, y_train, X_test, y_test):
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
    classifier = LogisticRegression()
    classifier.fit(X_train, y_train)
    metrics = classification_f1(classifier, X_test, y_test)
    return metrics

In [23]:
def Decision(X_train, y_train, X_test, y_test):
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.metrics import f1_score
    classifier = DecisionTreeClassifier()
    classifier.fit(X_train, y_train)
    f1 = classification_f1(classifier, X_test, y_test)
    return f1

In [24]:
def random(X_train, y_train, X_test,y_test):
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, random_state = 0)
        classifier.fit(X_train, y_train)
        accuracy = classification_f1((classifier, X_test, y_test))
        return accuracy

In [25]:
def xgboost(X_train, y_train, X_test):
        from xgboost import XGBClassifier
        classifier = XGBClassifier(n_jobs=5, learning_rate=0.1, max_depth=10, random_state=1)
        classifier.fit(X_train, y_train)
        accuracy = classification_f1((classifier, X_test, y_test))
        return accuracy

In [ ]:
"""from sklearn.feature_selection import RFE
def rfeFeature(indep_X, dep_Y, n):
    rfelist = []
    colnames_list = []
    # List to store column names for each model
    r2_values = []
    # List to store R2 values for each model

    from sklearn.linear_model import Linearclassfier
    lin = Linearclassfier()

    from sklearn.tree import DecisionTreeClassifier
    dec = DecisionTreeClassifier(random_state=0)

    from sklearn.ensemble import RandomForestClassifier
    rf = RandomForestClassifier(n_estimators=10, random_state=0)

    from xgboost import XGBClassifier
    xgb = XGBClassifier(n_jobs=5, learning_rate=0.1, max_depth=10, random_state=1)

    rfemodellist = [lin, dec, rf, xgb]

    for model in rfemodellist:
        log_rfe = RFE(estimator=model, n_features_to_select=n)
        log_fit = log_rfe.fit(indep_X, dep_Y)
        log_rfe_feature = log_fit.transform(indep_X)
        rfelist.append(log_rfe_feature)

        # Get the column names selected by RFE
        selected_columns = [col for col, selected in zip(indep_X.columns, log_rfe.support_) if selected]
        colnames_list.append(selected_columns)

        from sklearn.metrics import accuracy_score, f1_score

        # Fit the model and calculate and store the classification score
        X_train, X_test, y_train, y_test = split_scalar(pd.DataFrame(log_rfe_feature), dep_Y)
        model.fit(X_train, y_train)  # Fit the model

        # Predictions
        y_pred = model.predict(X_test)

        f1 = f1_score(y_test, y_pred, average="weighted")  # handles multi-class# Store results
        f1.append(f1)

        return rfelist, colnames_list, f1_score

# Return values: rfelist, colnames_list, scores_list
rfelist, colnames_list, scores_list = rfeFeature(X,y, 5)

# Print the selected column names and classification scores for each model
for model_name, selected_columns, scores in zip(["Logistic", "Decision", "Random", "XGBoost"], colnames_list, scores_list):
    acc, f1 = scores
    print(f"Model: {model_name}")
    print("Selected Columns:", selected_columns)
    print(f"Accuracy: {acc:.3f}, F1 Score: {f1:.3f}\n")
"""

'from sklearn.feature_selection import RFE\ndef rfeFeature(indep_X, dep_Y, n):\n    rfelist = []\n    colnames_list = []\n    # List to store column names for each model\n    r2_values = []\n    # List to store R2 values for each model\n\n    from sklearn.linear_model import Linearclassfier\n    lin = Linearclassfier()\n\n    from sklearn.tree import DecisionTreeClassifier\n    dec = DecisionTreeClassifier(random_state=0)\n\n    from sklearn.ensemble import RandomForestClassifier\n    rf = RandomForestClassifier(n_estimators=10, random_state=0)\n\n    from xgboost import XGBClassifier\n    xgb = XGBClassifier(n_jobs=5, learning_rate=0.1, max_depth=10, random_state=1)\n\n    rfemodellist = [lin, dec, rf, xgb]\n\n    for model in rfemodellist:\n        log_rfe = RFE(estimator=model, n_features_to_select=n)\n        log_fit = log_rfe.fit(indep_X, dep_Y)\n        log_rfe_feature = log_fit.transform(indep_X)\n        rfelist.append(log_rfe_feature)\n\n        # Get the column names selected by RFE\n        selected_columns = [col for col, selected in zip(indep_X.columns, log_rfe.support_) if selected]\n        colnames_list.append(selected_columns)\n\n        from sklearn.metrics import accuracy_score, f1_score\n\n        # Fit the model and calculate and store the classification score\n        X_train, X_test, y_train, y_test = split_scalar(pd.DataFrame(log_rfe_feature), dep_Y)\n        model.fit(X_train, y_train)  # Fit the model\n\n        # Predictions\n        y_pred = model.predict(X_test)\n\n        f1 = f1_score(y_test, y_pred, average="weighted")  # handles multi-class# Store results\n        f1.append(f1)\n\n        return rfelist, colnames_list, f1_score\n\n# Return values: rfelist, colnames_list, scores_list\nrfelist, colnames_list, scores_list = rfeFeature(X,y, 5)\n\n# Print the selected column names and classification scores for each model\nfor model_name, selected_columns, scores in zip(["Logistic", "Decision", "Random", "XGBoost"], colnames_list, scores_list):\n    acc, f1 = scores\n    print(f"Model: {model_name}")\n    print("Selected Columns:", selected_columns)\n    print(f"Accuracy: {acc:.3f}, F1 Score: {f1:.3f}\n")\n'

In [ ]:
"""from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split
import pandas as pd

def rfeFeature(indep_X, dep_Y, n):
    rfelist = []
    colnames_list = []
    scores_list = []  # will store (accuracy, f1) for each model

    # Convert categorical features to numerical using one-hot encoding
    indep_X_encoded = pd.get_dummies(indep_X, columns=['Airline', 'Source', 'Destination'])

    # Convert 'Duration' to numerical (assuming format 'Xh Ym')
    def parse_duration(duration_str):
        if isinstance(duration_str, str):
            parts = duration_str.split(' ')
            hours = 0
            minutes = 0
            for part in parts:
                if 'h' in part:
                    hours = int(part.replace('h', ''))
                elif 'm' in part:
                    minutes = int(part.replace('m', ''))
            return hours * 60 + minutes
        return 0  # Handle NaN or non-string

    indep_X_encoded['Duration'] = indep_X_encoded['Duration'].apply(parse_duration)

    # Define models
    lin = LogisticRegression(max_iter=1000, random_state=0)
    dec = DecisionTreeClassifier(random_state=0)
    rf = RandomForestClassifier(n_estimators=10, random_state=0)
    xgb = XGBClassifier(n_jobs=5, learning_rate=0.1, max_depth=10, random_state=1)

    rfemodellist = [lin, dec, rf, xgb]

    for model in rfemodellist:
        # Recursive Feature Elimination
        log_rfe = RFE(estimator=model, n_features_to_select=n)
        log_fit = log_rfe.fit(indep_X_encoded, dep_Y)  # Use encoded data
        log_rfe_feature = log_fit.transform(indep_X_encoded)
        rfelist.append(log_rfe_feature)

        # Selected feature names
        selected_columns = [col for col, selected in zip(indep_X_encoded.columns, log_rfe.support_) if selected]
        colnames_list.append(selected_columns)

        # Train/test split (replace split_scalar with sklearn train_test_split)
        X_train, X_test, y_train, y_test = train_test_split(
            log_rfe_feature, dep_Y, test_size=0.2, random_state=42, stratify=dep_Y
        )

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        # Scores
        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="weighted")
        scores_list.append((acc, f1))   # store tuple

    return rfelist, colnames_list, scores_list


# Example usage
rfelist, colnames_list, scores_list = rfeFeature(X, y, 5)

# Print results
for model_name, selected_columns, scores in zip(["Logistic", "Decision", "Random", "XGBoost"], colnames_list, scores_list):
    acc, f1 = scores
    print(f"Model: {model_name}")
    print("Selected Columns:", selected_columns)
    print(f"Accuracy: {acc:.3f}, F1 Score: {f1:.3f}\n")"""

'from sklearn.feature_selection import RFE\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\nfrom xgboost import XGBClassifier\nfrom sklearn.metrics import accuracy_score, f1_score\nfrom sklearn.model_selection import train_test_split\nimport pandas as pd\n\ndef rfeFeature(indep_X, dep_Y, n):\n    rfelist = []\n    colnames_list = []\n    scores_list = []  # will store (accuracy, f1) for each model\n\n    # Convert categorical features to numerical using one-hot encoding\n    indep_X_encoded = pd.get_dummies(indep_X, columns=[\'Airline\', \'Source\', \'Destination\'])\n\n    # Convert \'Duration\' to numerical (assuming format \'Xh Ym\')\n    def parse_duration(duration_str):\n        if isinstance(duration_str, str):\n            parts = duration_str.split(\' \')\n            hours = 0\n            minutes = 0\n            for part in parts:\n                if \'h\' in part:\n                    hours = int(part.replace(\'h\', \'\'))\n                elif \'m\' in part:\n                    minutes = int(part.replace(\'m\', \'\'))\n            return hours * 60 + minutes\n        return 0  # Handle NaN or non-string\n\n    indep_X_encoded[\'Duration\'] = indep_X_encoded[\'Duration\'].apply(parse_duration)\n\n    # Define models\n    lin = LogisticRegression(max_iter=1000, random_state=0)\n    dec = DecisionTreeClassifier(random_state=0)\n    rf = RandomForestClassifier(n_estimators=10, random_state=0)\n    xgb = XGBClassifier(n_jobs=5, learning_rate=0.1, max_depth=10, random_state=1)\n\n    rfemodellist = [lin, dec, rf, xgb]\n\n    for model in rfemodellist:\n        # Recursive Feature Elimination\n        log_rfe = RFE(estimator=model, n_features_to_select=n)\n        log_fit = log_rfe.fit(indep_X_encoded, dep_Y)  # Use encoded data\n        log_rfe_feature = log_fit.transform(indep_X_encoded)\n        rfelist.append(log_rfe_feature)\n\n        # Selected feature names\n        selected_columns = [col for col, selected in zip(indep_X_encoded.columns, log_rfe.support_) if selected]\n        colnames_list.append(selected_columns)\n\n        # Train/test split (replace split_scalar with sklearn train_test_split)\n        X_train, X_test, y_train, y_test = train_test_split(\n            log_rfe_feature, dep_Y, test_size=0.2, random_state=42, stratify=dep_Y\n        )\n\n        model.fit(X_train, y_train)\n        y_pred = model.predict(X_test)\n\n        # Scores\n        acc = accuracy_score(y_test, y_pred)\n        f1 = f1_score(y_test, y_pred, average="weighted")\n        scores_list.append((acc, f1))   # store tuple\n\n    return rfelist, colnames_list, scores_list\n\n\n# Example usage\nrfelist, colnames_list, scores_list = rfeFeature(X, y, 5)\n\n# Print results\nfor model_name, selected_columns, scores in zip(["Logistic", "Decision", "Random", "XGBoost"], colnames_list, scores_list):\n    acc, f1 = scores\n    print(f"Model: {model_name}")\n    print("Selected Columns:", selected_columns)\n    print(f"Accuracy: {acc:.3f}, F1 Score: {f1:.3f}\n")'

In [ ]:
"""from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split
import pandas as pd

def rfeFeature(indep_X, dep_Y, n):
    rfelist = []
    colnames_list = []
    scores_list = []  # will store (accuracy, f1) for each model

    # Convert categorical features to numerical using one-hot encoding
    indep_X_encoded = pd.get_dummies(indep_X, columns=['Airline', 'Source', 'Destination'])

    # Convert 'Duration' to numerical (assuming format 'Xh Ym')
    def parse_duration(duration_str):
        if isinstance(duration_str, str):
            parts = duration_str.split(' ')
            hours = 0
            minutes = 0
            for part in parts:
                if 'h' in part:
                    hours = int(part.replace('h', ''))
                elif 'm' in part:
                    minutes = int(part.replace('m', ''))
            return hours * 60 + minutes
        return 0  # Handle NaN or non-string

    indep_X_encoded['Duration'] = indep_X_encoded['Duration'].apply(parse_duration)

    # Define models
    lin = LogisticRegression(max_iter=1000, random_state=0)
    dec = DecisionTreeClassifier(random_state=0)
    rf = RandomForestClassifier(n_estimators=10, random_state=0)
    xgb = XGBClassifier(n_jobs=5, learning_rate=0.1, max_depth=10, random_state=1)

    rfemodellist = [lin, dec, rf, xgb]

    for model in rfemodellist:
        # Recursive Feature Elimination
        log_rfe = RFE(estimator=model, n_features_to_select=n)
        log_fit = log_rfe.fit(indep_X_encoded, dep_Y)  # Use encoded data
        log_rfe_feature = log_fit.transform(indep_X_encoded)
        rfelist.append(log_rfe_feature)

        # Selected feature names
        selected_columns = [col for col, selected in zip(indep_X_encoded.columns, log_rfe.support_) if selected]
        colnames_list.append(selected_columns)

        # Train/test split (replace split_scalar with sklearn train_test_split)
        X_train, X_test, y_train, y_test = train_test_split(
            log_rfe_feature, dep_Y, test_size=0.2, random_state=42, stratify=dep_Y
        )

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        # Scores
        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="weighted")
        scores_list.append((acc, f1))   # store tuple

    return rfelist, colnames_list, scores_list"""

'from sklearn.feature_selection import RFE\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\nfrom xgboost import XGBClassifier\nfrom sklearn.metrics import accuracy_score, f1_score\nfrom sklearn.model_selection import train_test_split\nimport pandas as pd\n\ndef rfeFeature(indep_X, dep_Y, n):\n    rfelist = []\n    colnames_list = []\n    scores_list = []  # will store (accuracy, f1) for each model\n\n    # Convert categorical features to numerical using one-hot encoding\n    indep_X_encoded = pd.get_dummies(indep_X, columns=[\'Airline\', \'Source\', \'Destination\'])\n\n    # Convert \'Duration\' to numerical (assuming format \'Xh Ym\')\n    def parse_duration(duration_str):\n        if isinstance(duration_str, str):\n            parts = duration_str.split(\' \')\n            hours = 0\n            minutes = 0\n            for part in parts:\n                if \'h\' in part:\n                    hours = int(part.replace(\'h\', \'\'))\n                elif \'m\' in part:\n                    minutes = int(part.replace(\'m\', \'\'))\n            return hours * 60 + minutes\n        return 0  # Handle NaN or non-string\n\n    indep_X_encoded[\'Duration\'] = indep_X_encoded[\'Duration\'].apply(parse_duration)\n\n    # Define models\n    lin = LogisticRegression(max_iter=1000, random_state=0)\n    dec = DecisionTreeClassifier(random_state=0)\n    rf = RandomForestClassifier(n_estimators=10, random_state=0)\n    xgb = XGBClassifier(n_jobs=5, learning_rate=0.1, max_depth=10, random_state=1)\n\n    rfemodellist = [lin, dec, rf, xgb]\n\n    for model in rfemodellist:\n        # Recursive Feature Elimination\n        log_rfe = RFE(estimator=model, n_features_to_select=n)\n        log_fit = log_rfe.fit(indep_X_encoded, dep_Y)  # Use encoded data\n        log_rfe_feature = log_fit.transform(indep_X_encoded)\n        rfelist.append(log_rfe_feature)\n\n        # Selected feature names\n        selected_columns = [col for col, selected in zip(indep_X_encoded.columns, log_rfe.support_) if selected]\n        colnames_list.append(selected_columns)\n\n        # Train/test split (replace split_scalar with sklearn train_test_split)\n        X_train, X_test, y_train, y_test = train_test_split(\n            log_rfe_feature, dep_Y, test_size=0.2, random_state=42, stratify=dep_Y\n        )\n\n        model.fit(X_train, y_train)\n        y_pred = model.predict(X_test)\n\n        # Scores\n        acc = accuracy_score(y_test, y_pred)\n        f1 = f1_score(y_test, y_pred, average="weighted")\n        scores_list.append((acc, f1))   # store tuple\n\n    return rfelist, colnames_list, scores_list'

In [ ]:
def rfeFeature_classification_fast(X, y, n):
    from sklearn.feature_selection import RFE
    from sklearn.linear_model import LogisticRegression
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    from xgboost import XGBClassifier
    from sklearn.metrics import accuracy_score, f1_score
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import LabelEncoder
    import pandas as pd
    import numpy as np

    # -----------------------------
    # 🔹 Ensure y is properly encoded
    # -----------------------------
    y = np.ravel(y)  # flatten to 1D
    le = LabelEncoder()
    y = le.fit_transform(y)  # ensures classes are 0...n-1

    # -----------------------------
    # 🔹 Preprocessing features
    # -----------------------------
    X = X.copy()

    def convert_duration_to_minutes(duration_str):
        if isinstance(duration_str, str):
            h, m = 0, 0
            if "h" in duration_str:
                h = int(duration_str.split("h")[0].strip())
                duration_str = duration_str.split("h")[1]
            if "m" in duration_str:
                m = int(duration_str.split("m")[0].strip())
            return h * 60 + m
        return duration_str

    for col in X.columns:
        if X[col].dtype == "object":
            try:
                X[col] = X[col].apply(convert_duration_to_minutes)
            except Exception:
                pass
            if X[col].dtype == "object":
                le = LabelEncoder()
                X[col] = le.fit_transform(X[col].astype(str))

    # -----------------------------
    # 🔹 RFE with Logistic Regression
    # -----------------------------
    base_model = LogisticRegression(max_iter=2000, solver="lbfgs", random_state=0)
    log_rfe = RFE(estimator=base_model, n_features_to_select=n, step=1)
    log_fit = log_rfe.fit(X, y)
    selected_columns = [col for col, selected in zip(X.columns, log_rfe.support_) if selected]
    X_selected = log_fit.transform(X)

    # -----------------------------
    # 🔹 Evaluate with multiple models
    # -----------------------------
    models = {
        "Logistic": LogisticRegression(max_iter=2000, solver="lbfgs", random_state=0),
        "Decision Tree": DecisionTreeClassifier(random_state=0),
        "Random Forest": RandomForestClassifier(n_estimators=10, n_jobs=-1, random_state=0),
        "XGBoost": XGBClassifier(n_estimators=50, max_depth=3, n_jobs=-1,
                                 use_label_encoder=False, eval_metric="logloss", random_state=0)
    }

    results = {}
    X_train, X_test, y_train, y_test = train_test_split(
        pd.DataFrame(X_selected), y, test_size=0.3, random_state=42
    )

    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="weighted")
        results[name] = {"Accuracy": acc, "F1": f1}

    return selected_columns, results

selected_columns, results = rfeFeature_classification_fast(X, y, 5)

print("Selected Columns:", selected_columns)
print("\nModel Results:")
for model, metrics in results.items():
    print(f"{model}: Accuracy = {metrics['Accuracy']:.4f}, F1 = {metrics['F1']:.4f}")