<a href="https://colab.research.google.com/github/Ragul-S-2025/ML/blob/main/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
data=pd.read_csv("/content/Naive-Bayes-Classification-Data.csv")
data

     glucose  bloodpressure  diabetes
0         40             85         0
1         40             92         0
2         45             63         1
3         45             80         0
4         40             73         1
..       ...            ...       ...
990       45             87         0
991       40             83         0
992       40             83         0
993       40             60         1
994       45             82         0

[995 rows x 3 columns]

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   glucose        995 non-null    int64
 1   bloodpressure  995 non-null    int64
 2   diabetes       995 non-null    int64
dtypes: int64(3)
memory usage: 23.4 KB

In [4]:
x=data[["glucose","bloodpressure"]]
x

     glucose  bloodpressure
0         40             85
1         40             92
2         45             63
3         45             80
4         40             73
..       ...            ...
990       45             87
991       40             83
992       40             83
993       40             60
994       45             82

[995 rows x 2 columns]

In [5]:
y=data["diabetes"]
y

0      0
1      0
2      1
3      0
4      1
      ..
990    0
991    0
992    0
993    1
994    0
Name: diabetes, Length: 995, dtype: int64

In [6]:

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x_train

     glucose  bloodpressure
909       45             90
925       45             78
974       40             78
765       25             73
911       40             72
..       ...            ...
106       45             75
270       55             67
860       35             78
435       40             93
102       45             95

[796 rows x 2 columns]

In [8]:
y_train

909    0
925    0
974    0
765    1
911    1
      ..
106    1
270    1
860    1
435    0
102    0
Name: diabetes, Length: 796, dtype: int64

In [9]:
x_test

     glucose  bloodpressure
920       40             70
525       40             75
567       45             65
657       45             93
633       45             88
..       ...            ...
486       50             83
451       35             72
65        45             87
141       45             80
685       45             92

[199 rows x 2 columns]

In [10]:
y_test

920    1
525    1
567    1
657    0
633    0
      ..
486    0
451    1
65     0
141    0
685    0
Name: diabetes, Length: 199, dtype: int64

In [11]:
# standard scalar for distance base

from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.fit_transform(x_test)

In [12]:
x_train

array([[ 0.10631451,  1.13952665],
       [ 0.10631451, -0.14556881],
       [-0.64927789, -0.14556881],
       ...,
       [-1.40487028, -0.14556881],
       [-0.64927789,  1.46080051],
       [ 0.10631451,  1.67498309]])

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
# Gausssian naive bayes
gnb = GaussianNB()
gnb.fit(x_train, y_train)

# Prediction
y_pred = gnb.predict(x_test)

print("GaussianNB Accuracy:", accuracy_score(y_test, y_pred))
r2 = r2_score(y_test, y_pred)
print("gussaiaanNB R² Score:", r2)

GaussianNB Accuracy: 0.9396984924623115
gussaiaanNB R² Score: 0.7577601947656725

In [21]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, r2_score

scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(x_train_scaled, y_train)
y_pred = mnb.predict(x_test_scaled)

acc = accuracy_score(y_test, y_pred)

# R² Score (not usually used for classification, but you asked)
r2 = r2_score(y_test, y_pred)

print("MultinomialNB Accuracy:", acc)
print("MultinomialNB R² Score:", r2)

MultinomialNB Accuracy: 0.7386934673366834
MultinomialNB R² Score: -0.049705822682085676

In [22]:
from sklearn.naive_bayes import BernoulliNB
scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

bnb = BernoulliNB()
bnb.fit(x_train_scaled, y_train)
y_pred = bnb.predict(x_test_scaled)

print("BernoulliNB Accuracy:", accuracy_score(y_test, y_pred))
print("BernoulliNB R²:", r2_score(y_test, y_pred))

BernoulliNB Accuracy: 0.46733668341708545
BernoulliNB R²: -1.1397849462365595

In [23]:
from sklearn.naive_bayes import ComplementNB

scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

cnb = ComplementNB()
cnb.fit(x_train_scaled, y_train)
y_pred = cnb.predict(x_test_scaled)

print("ComplementNB Accuracy:", accuracy_score(y_test, y_pred))
print("ComplementNB R²:", r2_score(y_test, y_pred))

ComplementNB Accuracy: 0.7939698492462312
ComplementNB R²: 0.1723473321160478

In [25]:
from sklearn.naive_bayes import CategoricalNB
import numpy as np

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

x_train_cat = np.round(x_train_scaled * 3).astype(int)
x_test_cat = np.round(x_test_scaled * 3).astype(int)

catnb = CategoricalNB()
catnb.fit(x_train_cat, y_train)
y_pred = catnb.predict(x_test_cat)

print("CategoricalNB Accuracy:", accuracy_score(y_test, y_pred))
print("CategoricalNB R²:", r2_score(y_test, y_pred))

CategoricalNB Accuracy: 0.8291457286432161
CategoricalNB R²: 0.3136538851694055